### ISSUE TITLE
Unable to get it work with proxied/custom api

### ISSUE THREAD

**Issue by AbhayGhante** [soyelmismo/chatgpTG#4]
Error logs:

FileNotFoundError: [Errno 2] No such file or directory: '/config/lang.yml'
[nltk_data] Downloading package names to /root/nltk_data...
[nltk_data]   Package names is already up-to-date!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/bot/__main__.py", line 1, in <module>
    from bot.src.start import run_bot
  File "/bot/src/start.py", line 13, in <module>
    from .handlers import message, voice, ocr_image, document, timeout, error
  File "/bot/src/handlers/message.py", line 6, in <module>
    from bot.src.utils.gen_utils.phase import ChatGPT
  File "/bot/src/utils/gen_utils/phase.py", line 1, in <module>
    from bot.src.utils import proxies
  File "/bot/src/utils/proxies.py", line 3, in <module>
    from bot.src.utils import config, database
  File "/bot/src/utils/config.py", line 47, in <module>
    with open(config_dir / "lang.yml", 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/config/lang.yml

**Comment by soyelmismo** [comment]
oof im sorry. it was a misspelling in the docker-compose file. now it should work normally

please apply [these changes](https://github.com/soyelmismo/chatgpTG/commit/55058ccc8b2df2b62c32aaa38512f2f8d4037477) to your docker-compose file and try again

**Comment by AbhayGhante** [comment]
yet new error log 

FileNotFoundError: [Errno 2] No such file or directory: '/config/props.yml'
[nltk_data] Downloading package names to /root/nltk_data...
[nltk_data]   Package names is already up-to-date!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/bot/__main__.py", line 1, in <module>
    from bot.src.start import run_bot
  File "/bot/src/start.py", line 13, in <module>
    from .handlers import message, voice, ocr_image, document, timeout, error
  File "/bot/src/handlers/message.py", line 6, in <module>
    from bot.src.utils.gen_utils.phase import ChatGPT
  File "/bot/src/utils/gen_utils/phase.py", line 1, in <module>
    from bot.src.utils import proxies
  File "/bot/src/utils/proxies.py", line 3, in <module>
    from bot.src.utils import config, database
  File "/bot/src/utils/config.py", line 67, in <module>
    with open(config_dir / "props.yml", 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/config/props.yml'
[nltk_data] Downloading package names to /root/nltk_data...
[nltk_data]   Package names is already up-to-date!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/bot/__main__.py", line 1, in <module>
    from bot.src.start import run_bot
  File "/bot/src/start.py", line 13, in <module>
    from .handlers import message, voice, ocr_image, document, timeout, error
  File "/bot/src/handlers/message.py", line 6, in <module>
    from bot.src.utils.gen_utils.phase import ChatGPT
  File "/bot/src/utils/gen_utils/phase.py", line 1, in <module>
    from bot.src.utils import proxies
  File "/bot/src/utils/proxies.py", line 3, in <module>
    from bot.src.utils import config, database
  File "/bot/src/utils/config.py", line 67, in <module>
    with open(config_dir / "props.yml", 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by soyelmismo** [comment]
Make sure you have all the yml files inside the config directory, it claims props is not there, but it's already on the repo

**Comment by soyelmismo** [comment]
And there's no updated Dockerfile in your fork

**Comment by AbhayGhante** [comment]
Oh yh, I forgot to remv old docker built image, but still after everything, This error logs 
 
 
  File "/usr/local/lib/python3.11/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/config/api.yml", line 6, column 3
expected <block end>, but found '<block mapping start>'
  in "/config/api.yml", line 129, column 4
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/bot/__main__.py", line 1, in <module>
    from bot.src.start import run_bot
  File "/bot/src/start.py", line 13, in <module>
    from .handlers import message, voice, ocr_image, document, timeout, error
  File "/bot/src/handlers/message.py", line 6, in <module>
    from bot.src.utils.gen_utils.phase import ChatGPT
  File "/bot/src/utils/gen_utils/phase.py", line 1, in <module>
    from bot.src.utils import proxies
  File "/bot/src/utils/proxies.py", line 3, in <module>
    from bot.src.utils import config, database
  File "/bot/src/utils/config.py", line 52, in <module>
    api = yaml.safe_load(f)
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/config/api.yml", line 6, column 3
expected <block end>, but found '<block mapping start>'
  in "/config/api.yml", line 129, column 4

**Comment by soyelmismo** [comment]
Keep the correct indentation in the yml files. Check the other API you added and count the spaces

**Comment by AbhayGhante** [comment]
> Keep the correct indentation in the yml files. Check the other API you added and count the spaces

oh oky wait

**Comment by AbhayGhante** [comment]
yeah deployed it successfully. Thanks

**Comment by AbhayGhante** [comment]
the only issue with telegram is that, when the chatgpt gen response with tables or codes it isn't readable

**Comment by soyelmismo** [comment]
Yeh sorry, it's hard to make telegram interpret well the markdown code while it's editing the message in real time I think.
i already tried to only markdown it when it ends the response but it still giving errors, do i disabled the markdown parsing to avoid errors...

Idk how to fix it at the moment

**Comment by AbhayGhante** [comment]
> Yeh sorry, it's hard to make telegram interpret well the markdown code while it's editing the message in real time I think. i already tried to only markdown it when it ends the response but it still giving errors, so i disabled the markdown parsing to avoid errors...
> 
> Idk how to fix it at the moment

But you did a great job making this compatible to work with custom Api. Thank You
